services:
  lasertag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lasertag
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
    name: proxy_network
